# -*- coding: utf-8 -*-
"""small scale Gen AI Project Transformers.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PIJwdNwqZZUR4EAaPGH4v-MiV4lWgNB2
"""

#import libraries needed for text encoding, text similarity, chat user interface.

#Used to convert text into numerical vectors, Helps machines understand meaning of sentences.
from sentence_transformers import SentenceTransformer

#machine learning,classification,regression,clustering,similarity calculations,preprocessing.
from sklearn.metrics.pairwise import cosine_similarity

#numerical computing. Works with arrays,matrices,math,fast vector & matrix calculations.
import numpy as np

#work with tables,reading data,filtering,cleaning,manipulating datasets.
import pandas as pd

#create interactive UI elements in web IDE,text boxes,buttons,sliders,dropdowns.
import ipywidgets as widgets

#display items inside notebooks - widgets, images, HTML, tables.
from IPython.display import display

# loading the sentence transformer model.
model = SentenceTransformer("all-MiniLM-L6-v2")

# creating dictionary with list of product names and list of corresponding product details.
data = {
"product":[
"wireless mouse",
"gaming keyboard",
"bluetooth headphones",
"power bank",
"smart watch",
"laptop stand",
"usb c hub",
"external hard drive",
"gaming mouse",
"monitor",
"mechanical keyboard",
"gaming headset",
"tablet",
"laptop",
"smartphone",
"webcam",
"microphone",
"portable speaker",
"ssd drive",
"router",
"smart tv",
"led tv",
"refrigerator",
"washing machine",
"air conditioner",
"microwave oven",
"electric kettle",
"coffee maker",
"blender",
"induction stove",
"printer",
"scanner",
"digital camera",
"dslr camera",
"tripod",
"graphics tablet",
"vr headset",
"projector",
"desk lamp",
"office chair",
"tv"
],

"description":[
"Wireless mouse connects using bluetooth or USB receiver with long battery life.",
"Gaming keyboard has mechanical switches and RGB lighting for gaming.",
"Bluetooth headphones provide wireless audio and noise cancellation.",
"Power bank is a portable charger used to charge phones and tablets.",
"Smart watch tracks fitness, heart rate, steps and notifications.",
"Laptop stand improves posture and cooling for laptops.",
"USB C hub expands ports with HDMI USB and SD card slots.",
"External hard drive stores large files and backups.",
"Gaming mouse offers high DPI sensor and programmable buttons.",
"Full HD monitor provides clear display for work and gaming.",
"Mechanical keyboard provides tactile feedback and durability.",
"Gaming headset delivers surround sound and microphone support.",
"Tablet is a portable touchscreen device for entertainment and work.",
"Laptop is a portable computer used for work study and browsing.",
"Smartphone is a mobile phone with apps internet and camera.",
"Webcam is used for video calls and online meetings.",
"Microphone captures clear audio for streaming and recording.",
"Portable speaker plays wireless music using bluetooth.",
"SSD drive provides fast storage for computers and laptops.",
"Router provides wireless internet connectivity in homes and offices.",
"Smart TV connects to the internet and streams content from apps like Netflix and YouTube.",
"LED TV provides bright display with energy efficient LED technology.",
"Refrigerator keeps food fresh using cooling and freezing compartments.",
"Washing machine automatically washes clothes with multiple wash programs.",
"Air conditioner cools rooms and controls indoor temperature.",
"Microwave oven heats and cooks food quickly using microwave energy.",
"Electric kettle quickly boils water for tea coffee or cooking.",
"Coffee maker brews fresh coffee automatically.",
"Blender mixes fruits vegetables and ingredients for smoothies and juices.",
"Induction stove cooks food using electromagnetic heating technology.",
"Printer prints documents and photos from computers and phones.",
"Scanner converts paper documents into digital files.",
"Digital camera captures high quality photos and videos.",
"DSLR camera provides professional photography with interchangeable lenses.",
"Tripod stabilizes cameras for photography and video recording.",
"Graphics tablet allows digital drawing and design on computers.",
"VR headset provides immersive virtual reality gaming experience.",
"Projector displays large screen images for movies and presentations.",
"Desk lamp provides focused lighting for study or work.",
"Office chair provides ergonomic support for long working hours.",
"Sure, would you like to go for LED TV or LCD TV?"
]
}

print(data)

#converting the dictionary with list of product, list of description into a table with 2 columns and rows.
df = pd.DataFrame(data)
print(df)

#product column and description column  is combined into single dataframe table with rows for the model to create similar vectors for each words in same row.
combined = df["product"] + " " + df["description"]
print(combined)

#applying the text to numerical vector conversion model into the combined dataset.
product_embeddings = model.encode(combined.tolist())
print(product_embeddings)

#creating general list of user messages for chat to understand and reply customer humanly.

greetings = ["hi","hello","hey","are you there","anyone"]
courtesy = ["okay","thank you","thanks","i will buy","fine","alright"]
bye_words = ["bye","goodbye","see you","thats all","thats all thanks","thats it"]
how_are_you_phrases = ["how are you","how its going","how is it going","how are you doing","how is your day","how have you been","hows everything","everything good"]

# Welcome Chat Message.(created using HTML because we are using HTML Chat box).
chat_history = "<div style='text-align:left;margin:8px;color:darkblue'><b>Joseph AI Chat:</b> Hello! I am your AI product specialist. Please ask me about any product you are interested in.</div>"

# Chat box (created using HTML because we are using HTML Chat box).
chat_area = widgets.HTML(
value=f"<div style='height:420px;width:520px;border:1px solid gray;padding:10px;overflow:auto;background:#f9f9f9'>{chat_history}</div>"
)

# creating input box for user to type message.
input_box = widgets.Text(
placeholder="Ask about a product..."
)

#creating send button for user to send message.
send_button = widgets.Button(description="Send")

#creating a function for chatbot to take input and how to respond back.
def chatbot_response(message):
    user_msg = message.lower()

    #Convert user question to vector numbers called embedding.
    query_embedding = model.encode([user_msg])

    #finding vector similarities of question and answers using cosine.
    #words matching with question will have higher values.
    similarities = cosine_similarity(query_embedding, product_embeddings)

    #taking out the index number of the highest matching value.
    best_match = np.argmax(similarities)

    #now the index for question is row 0 since there is one row/one question.
    #index for highest matching value is stored in best_match.
    #we find the similarity value present in both row index, column index.
    score = similarities[0][best_match]

    # If question to product details match is good, then return product details
    if score >= 0.20:

        #using iloc to take out the best matching values from product and description.
        product = df.iloc[best_match]["product"]
        description = df.iloc[best_match]["description"]

        return f"Great! I recommend, {product.title()}: {description}"

    #response if user sends hi, hello messages.
    if any(word in user_msg for word in greetings):
        return "Hello! Hope you have a great day. Happy to answer your questions"

    #response if user sends how are you.
    if any(word in user_msg for word in how_are_you_phrases):
        return "I'm doing great! How can I help you today?"

    #response if user shares their preferences.
    if "like" or "love" or "mostly" or "hardly" or "sometimes" or "need" in user_msg:
        return "Great, thats great to hear!"

    #response if user send thanks etc.
    if any(word in user_msg for word in courtesy):
        return "Great! I am here if you have anymore questions"

    #response if user send bye etc.
    if any(word in user_msg for word in bye_words):
        return "Its a pleasure to assist you. Goodbye! Have a nice day."

    #response if user send any message other than what is predicted above.
    return "Sorry, I do not have that  information available yet."

#creating function for chat input appearance.
def send_message(b):

    #global asks the function to use chat_history variable which is already present outside the function.
    global chat_history

    #values entered in input_box will be taken as user text.
    user_text = input_box.value

    #if user did not type anything and click send, stop the function.
    if user_text == "":
        return

    #now user text is sent to Chatbot_response function, it will run and store the result in bot_reply
    bot_reply = chatbot_response(user_text)

    #user message will be added to the Chat_history.
    chat_history += f"<div style='text-align:right;margin:8px'><b>You:</b> {user_text}</div>"

    #bot_reply message will also be added to the chat_history.
    chat_history += f"<div style='text-align:left;margin:8px;color:darkblue'><b>Joseph AI:</b> {bot_reply}</div>"

    #Creating background for chat interface using HTML by iPywidget library.
    chat_area.value = f"<div style='height:420px;width:520px;border:1px solid gray;border-radius:10px;padding:10px;overflow:auto;background:#f9f9f9'>{chat_history}</div>"

    #value in input_box will be empty by default.
    input_box.value = ""


#clicking Send_button will start the send_message function.
send_button.on_click(send_message)

#Pressing Enter in Input_box will start the send_message function too.
input_box.on_submit(send_message)

#show chat area, input box, send button.
display(chat_area, input_box, send_button)